name: Make it Taylor's Version

permissions:
  issues: write
  pull-requests: write
  discussions: write

on:
  issues:
    types:
     - opened
  pull_request:
    types:
     - opened
     - ready_for_review
  discussion:
    types:
     - created

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const suffix='Taylor\'s Version';
            const item=context.payload.issue||context.payload.pull_request||context.payload.discussion;
            if(item.number!==1989||item.title.includes(suffix))return;
            const newTitle=`${item.title} (${suffix})`;
            context.payload.issue?github.rest.issues.update({owner:context.repo.owner,repo:context.repo.repo,issue_number:item.number,title:newTitle}):context.payload.pull_request?github.rest.pulls.update({owner:context.repo.owner,repo:context.repo.repo,pull_number:item.number,title:newTitle}):github.graphql(`mutation{updateDiscussion(input:{discussionId:"${item.node_id}",title:"${newTitle}"}){discussion{title}}}`)
