name: Make it Taylor's Version

permissions:
  issues: write
  pull-requests: write
  discussions: write

on:
  issues:
    types:
     - opened
  pull_request:
    types:
     - opened
     - ready_for_review
  discussion:
    types:
     - created

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const t='Taylor\'s Version',i=context.payload.issue,p=context.payload.pull_request,d=context.payload.discussion,x=i||p||d;if(x.number!==1989||~x.title.indexOf(t))return;i?github.rest.issues.update({owner:context.repo.owner,repo:context.repo.repo,issue_number:x.number,title:`${x.title} (${t})`}):p?github.rest.pulls.update({owner:context.repo.owner,repo:context.repo.repo,pull_number:x.number,title:`${x.title} (${t})`}):d&&github.graphql(`mutation{updateDiscussion(input:{discussionId:"${x.node_id}",title:"${x.title} (${t})"}){discussion{title}}}`)
